name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :debugpanel-core:assembleRelease

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: debugpanel-core-aar
          path: debugpanel-core/build/outputs/aar/debugpanel-core-release.aar